# CatBoost


## Importing the libraries


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset


In [2]:
dataset = pd.read_csv('data/processed/BTC_USDT_1m_model_ready.csv')
X = dataset.iloc[:, 1:-3].values
y = dataset.iloc[:, -1].values
y = np.array(y)

## Splitting the dataset into the Training set and Test set


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training CatBoost on the Training set


In [4]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)

Learning rate set to 0.113885
0:	learn: 0.8919578	total: 175ms	remaining: 2m 55s
1:	learn: 0.7445986	total: 342ms	remaining: 2m 50s
2:	learn: 0.6326586	total: 494ms	remaining: 2m 44s
3:	learn: 0.5444655	total: 644ms	remaining: 2m 40s
4:	learn: 0.4730772	total: 822ms	remaining: 2m 43s
5:	learn: 0.4144384	total: 973ms	remaining: 2m 41s
6:	learn: 0.3653456	total: 1.12s	remaining: 2m 39s
7:	learn: 0.3240012	total: 1.27s	remaining: 2m 37s
8:	learn: 0.2889649	total: 1.42s	remaining: 2m 36s
9:	learn: 0.2589003	total: 1.56s	remaining: 2m 34s
10:	learn: 0.2330326	total: 1.71s	remaining: 2m 33s
11:	learn: 0.2107263	total: 1.84s	remaining: 2m 31s
12:	learn: 0.1914250	total: 1.99s	remaining: 2m 30s
13:	learn: 0.1746498	total: 2.11s	remaining: 2m 28s
14:	learn: 0.1600361	total: 2.25s	remaining: 2m 27s
15:	learn: 0.1472823	total: 2.38s	remaining: 2m 26s
16:	learn: 0.1361402	total: 2.52s	remaining: 2m 25s
17:	learn: 0.1263176	total: 2.66s	remaining: 2m 25s
18:	learn: 0.1179133	total: 2.8s	remaining: 

CatBoostClassifier()

## Making the Confusion Matrix


In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[    85   1813      6]
 [    38 311407     18]
 [     6   1904     45]]


0.9879963973335194

## Applying k-Fold Cross Validation


In [6]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Learning rate set to 0.113274
0:	learn: 0.8929954	total: 112ms	remaining: 1m 51s
1:	learn: 0.7461148	total: 256ms	remaining: 2m 7s
2:	learn: 0.6343999	total: 383ms	remaining: 2m 7s
3:	learn: 0.5463063	total: 512ms	remaining: 2m 7s
4:	learn: 0.4749423	total: 633ms	remaining: 2m 5s
5:	learn: 0.4163546	total: 761ms	remaining: 2m 6s
6:	learn: 0.3672087	total: 894ms	remaining: 2m 6s
7:	learn: 0.3257892	total: 1.02s	remaining: 2m 6s
8:	learn: 0.2906720	total: 1.15s	remaining: 2m 6s
9:	learn: 0.2605237	total: 1.27s	remaining: 2m 6s
10:	learn: 0.2345663	total: 1.43s	remaining: 2m 8s
11:	learn: 0.2121628	total: 1.55s	remaining: 2m 7s
12:	learn: 0.1927705	total: 1.67s	remaining: 2m 7s
13:	learn: 0.1759055	total: 1.79s	remaining: 2m 6s
14:	learn: 0.1612051	total: 1.92s	remaining: 2m 6s
15:	learn: 0.1483699	total: 2.04s	remaining: 2m 5s
16:	learn: 0.1371112	total: 2.15s	remaining: 2m 4s
17:	learn: 0.1273112	total: 2.26s	remaining: 2m 3s
18:	learn: 0.1186751	total: 2.38s	remaining: 2m 3s
19:	learn:

In [7]:
from pathlib import Path

# Save trained CatBoost model
model_dir = Path("models")
model_dir.mkdir(parents=True, exist_ok=True)

model_path = model_dir / "catboost_classifier.cbm"
classifier.save_model(str(model_path))

print(f"Model saved to: {model_path}")

Model saved to: models/catboost_classifier.cbm
